version: 2

models:

  - name: fact_event
    description: This table includes details of events from users
    columns:
      - name: event_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
