version: 2

models:
  - name: dim_user
    description: This table includes details of users from each firm
    columns:
      - name: user_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: dim_firm
    description: This table includes details of each firm
    columns:
      - name: firm_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
